/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Observations
         * @description Get a list of all telescope observations for the authenticated user.
         */
        get: operations["list_observations_v1_observations__get"];
        put?: never;
        /**
         * Submit Observation
         * @description Submit a new telescope observation request.
         */
        post: operations["submit_observation_v1_observations__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Observation
         * @description Get details of a specific telescope observation by ID.
         */
        get: operations["get_observation_v1_observations__observation_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Observation
         * @description Cancel a pending telescope observation request.
         */
        delete: operations["cancel_observation_v1_observations__observation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for the API.
         */
        get: operations["health_check_v1_web_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description Get overall system status including telescope and observation queue info.
         */
        get: operations["get_system_status_v1_web_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint providing basic API information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_submit_observation_v1_observations__post */
        Body_submit_observation_v1_observations__post: {
            observation: components["schemas"]["ObservationCreate"];
            requestor: components["schemas"]["UserCreate"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ObservationCreate
         * @description Schema for creating a new observation (API request).
         * @example {
         *       "bb_gain": 10,
         *       "center_frequency": 1400,
         *       "dec": 41.26875,
         *       "if_gain": 20,
         *       "integration_time": 600,
         *       "observation_object": "Andromeda Galaxy",
         *       "observation_type": "target_observation",
         *       "output_filename": "m31_observation.fits",
         *       "ra": 10.68470833,
         *       "rf_gain": 30,
         *       "target_name": "M31"
         *     }
         */
        ObservationCreate: {
            /**
             * Target Name
             * @description Name of the observation target
             */
            target_name: string;
            /**
             * Observation Object
             * @description Object being observed
             */
            observation_object: string;
            /**
             * Ra
             * @description Right Ascension in degrees
             */
            ra: number;
            /**
             * Dec
             * @description Declination in degrees
             */
            dec: number;
            /**
             * Center Frequency
             * @description Center frequency in MHz
             */
            center_frequency: number;
            /**
             * Rf Gain
             * @description RF gain in dB
             */
            rf_gain: number;
            /**
             * If Gain
             * @description IF gain in dB
             */
            if_gain: number;
            /**
             * Bb Gain
             * @description Baseband gain in dB
             */
            bb_gain: number;
            /**
             * @description Type of observation
             * @default target_observation
             */
            observation_type: components["schemas"]["ObservationType"];
            /**
             * Integration Time
             * @description Integration time in seconds
             */
            integration_time: number;
            /**
             * Output Filename
             * @description Filename for the observation data
             */
            output_filename: string;
        };
        /**
         * ObservationRead
         * @description Schema for reading an observation (API response).
         * @example {
         *       "bb_gain": 10,
         *       "center_frequency": 1400,
         *       "dec": 41.26875,
         *       "if_gain": 20,
         *       "integration_time": 600,
         *       "observation_id": "obs_20231110_001",
         *       "observation_object": "Andromeda Galaxy",
         *       "observation_type": "target_observation",
         *       "output_filename": "m31_observation.fits",
         *       "ra": 10.68470833,
         *       "rf_gain": 30,
         *       "status": "pending",
         *       "submitted_at": "2023-11-10T12:34:56Z",
         *       "target_name": "M31",
         *       "user_id": 42
         *     }
         */
        ObservationRead: {
            /**
             * Target Name
             * @description Name of the observation target
             */
            target_name: string;
            /**
             * Observation Object
             * @description Object being observed
             */
            observation_object: string;
            /**
             * Ra
             * @description Right Ascension in degrees
             */
            ra: number;
            /**
             * Dec
             * @description Declination in degrees
             */
            dec: number;
            /**
             * Center Frequency
             * @description Center frequency in MHz
             */
            center_frequency: number;
            /**
             * Rf Gain
             * @description RF gain in dB
             */
            rf_gain: number;
            /**
             * If Gain
             * @description IF gain in dB
             */
            if_gain: number;
            /**
             * Bb Gain
             * @description Baseband gain in dB
             */
            bb_gain: number;
            /**
             * @description Type of observation
             * @default target_observation
             */
            observation_type: components["schemas"]["ObservationType"];
            /**
             * Integration Time
             * @description Integration time in seconds
             */
            integration_time: number;
            /**
             * Output Filename
             * @description Filename for the observation data
             */
            output_filename: string;
            /**
             * Observation Id
             * @description Unique observation identifier
             */
            observation_id: string;
            /**
             * User Id
             * @description ID of the user who submitted the observation
             */
            user_id: number;
            /** @description Current observation status */
            status: components["schemas"]["ObservationStatus"];
            /**
             * Submitted At
             * Format: date-time
             * @description Timestamp of submission
             */
            submitted_at: string;
            /**
             * Completed At
             * @description Timestamp of completion
             */
            completed_at?: string | null;
        };
        /**
         * ObservationStatus
         * @description Enumeration for the status of an observation.
         * @enum {string}
         */
        ObservationStatus: "pending" | "in_progress" | "completed" | "failed" | "cancelled";
        /**
         * ObservationType
         * @description Enumeration for the type of an observation.
         * @enum {string}
         */
        ObservationType: "hot_calibration" | "cold_calibration" | "target_observation";
        /**
         * StatusResponse
         * @description Generic status response for health checks and system status.
         * @example {
         *       "data": {
         *         "active_observations": 3,
         *         "uptime": 86400
         *       },
         *       "message": "System is operational",
         *       "status": "healthy"
         *     }
         */
        StatusResponse: {
            /**
             * Status
             * @description Status indicator
             */
            status: string;
            /**
             * Message
             * @description Optional message
             */
            message?: string | null;
            /**
             * Data
             * @description Optional data payload
             */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * UserCreate
         * @description Schema for creating a new user (API request).
         * @example {
         *       "email": "software@astrobeam.gr",
         *       "user_id": "123456",
         *       "username": "astro_test_user"
         *     }
         */
        UserCreate: {
            /**
             * User Id
             * @description Unique user identifier
             */
            user_id: string;
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Email
             * Format: email
             * @description Email address
             */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_observations_v1_observations__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of observations retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationRead"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit_observation_v1_observations__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_submit_observation_v1_observations__post"];
            };
        };
        responses: {
            /** @description Observation request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Telescope service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_observation_v1_observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observation details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationRead"];
                };
            };
            /** @description Observation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_observation_v1_observations__observation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observation cancelled successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Observation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_v1_web_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_system_status_v1_web_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System status retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
}
