/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/v1/observations/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Observations
		 * @description Get a list of all telescope observations for the authenticated user.
		 */
		get: operations["list_observations_v1_observations__get"];
		put?: never;
		/**
		 * Submit Observation
		 * @description Submit a new telescope observation request.
		 */
		post: operations["submit_observation_v1_observations__post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/observations/{observation_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Observation
		 * @description Get details of a specific telescope observation by ID.
		 */
		get: operations["get_observation_v1_observations__observation_id__get"];
		put?: never;
		post?: never;
		/**
		 * Cancel Observation
		 * @description Cancel a pending telescope observation request.
		 */
		delete: operations["cancel_observation_v1_observations__observation_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/web/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Health check endpoint for the API.
		 */
		get: operations["health_check_v1_web_health_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/web/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get System Status
		 * @description Get overall system status including telescope and observation queue info.
		 */
		get: operations["get_system_status_v1_web_status_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Root
		 * @description Root endpoint providing basic API information.
		 */
		get: operations["root__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * BandwidthEnum
		 * @description Enumeration for observation bandwidths around the central frequencies.
		 * @enum {number}
		 */
		BandwidthEnum:
			| 1.5
			| 1.75
			| 2.5
			| 2.75
			| 3
			| 3.84
			| 5.5
			| 6
			| 7
			| 8.75
			| 10
			| 12
			| 14
			| 20
			| 28;
		/**
		 * CentralFrequencyEnum
		 * @description Enumeration for central frequencies.
		 * @enum {number}
		 */
		CentralFrequencyEnum: 1420 | 1670 | 22000;
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/**
		 * ObservationCreate
		 * @description Schema for creating a new observation (API request).
		 * @example {
		 *       "bandwidth": 20,
		 *       "center_frequency": 1420,
		 *       "dec": 41.26875,
		 *       "fft_size": 1024,
		 *       "integration_time": 600,
		 *       "observation_type": "TARGET_OBSERVATION",
		 *       "output_filename": "m31_observation",
		 *       "perform_data_analysis": true,
		 *       "planned_start": "2026-11-15T20:00:00",
		 *       "ra": 10.68470833,
		 *       "receive_csv": false,
		 *       "target_name": "M31",
		 *       "velocity_frame": "LSRK"
		 *     }
		 */
		ObservationCreate: {
			/**
			 * Target Name
			 * @description Name of the observation target
			 */
			target_name: string | null;
			/**
			 * Ra
			 * @description Right Ascension in degrees
			 */
			ra: number;
			/**
			 * Dec
			 * @description Declination in degrees
			 */
			dec: number;
			/**
			 * @description Bandwidth in MHz
			 * @default 1.5
			 */
			bandwidth: components["schemas"]["BandwidthEnum"];
			/**
			 * @description Center frequency in MHz
			 * @default 1420
			 */
			center_frequency: components["schemas"]["CentralFrequencyEnum"];
			/**
			 * @description Velocity reference frame
			 * @default LSRK
			 */
			velocity_frame: components["schemas"]["ReferenceFrameEnum"];
			/**
			 * @description Type of observation
			 * @default TARGET_OBSERVATION
			 */
			observation_type: components["schemas"]["ObservationTypeEnum"];
			/**
			 * Fft Size
			 * @description FFT size for spectral observations
			 * @default 1024
			 */
			fft_size: number;
			/**
			 * Integration Time
			 * @description Integration time in seconds
			 */
			integration_time: number;
			/**
			 * Planned Start
			 * @description Planned start time for the observation
			 */
			planned_start?: string | null;
			/**
			 * Output Filename
			 * @description Filename for the observation data
			 */
			output_filename: string;
			/**
			 * Receive Csv
			 * @description Whether the user wants to receive a CSV containing frequency-power pairs
			 * @default false
			 */
			receive_csv: boolean;
			/**
			 * Perform Data Analysis
			 * @description Whether to perform data analysis and generate plots
			 * @default true
			 */
			perform_data_analysis: boolean;
		};
		/**
		 * ObservationRead
		 * @description Schema for reading an observation (API response).
		 * @example {
		 *       "bandwidth": 20,
		 *       "center_frequency": 1420,
		 *       "created_on": "2026-11-10T12:34:56",
		 *       "dec": 41.26875,
		 *       "fft_size": 1024,
		 *       "id": 13,
		 *       "integration_time": 600,
		 *       "observation_type": "TARGET_OBSERVATION",
		 *       "output_filename": "m31_observation",
		 *       "perform_data_analysis": true,
		 *       "planned_start": "2026-11-15T20:00:00",
		 *       "ra": 10.68470833,
		 *       "receive_csv": false,
		 *       "status": "PENDING",
		 *       "target_name": "M31",
		 *       "updated_on": "2026-11-10T13:34:56",
		 *       "user_id": 42,
		 *       "velocity_frame": "LSRK"
		 *     }
		 */
		ObservationRead: {
			/**
			 * Target Name
			 * @description Name of the observation target
			 */
			target_name: string | null;
			/**
			 * Ra
			 * @description Right Ascension in degrees
			 */
			ra: number;
			/**
			 * Dec
			 * @description Declination in degrees
			 */
			dec: number;
			/**
			 * @description Bandwidth in MHz
			 * @default 1.5
			 */
			bandwidth: components["schemas"]["BandwidthEnum"];
			/**
			 * @description Center frequency in MHz
			 * @default 1420
			 */
			center_frequency: components["schemas"]["CentralFrequencyEnum"];
			/**
			 * @description Velocity reference frame
			 * @default LSRK
			 */
			velocity_frame: components["schemas"]["ReferenceFrameEnum"];
			/**
			 * @description Type of observation
			 * @default TARGET_OBSERVATION
			 */
			observation_type: components["schemas"]["ObservationTypeEnum"];
			/**
			 * Fft Size
			 * @description FFT size for spectral observations
			 * @default 1024
			 */
			fft_size: number;
			/**
			 * Integration Time
			 * @description Integration time in seconds
			 */
			integration_time: number;
			/**
			 * Planned Start
			 * @description Planned start time for the observation
			 */
			planned_start?: string | null;
			/**
			 * Output Filename
			 * @description Filename for the observation data
			 */
			output_filename: string;
			/**
			 * Receive Csv
			 * @description Whether the user wants to receive a CSV containing frequency-power pairs
			 * @default false
			 */
			receive_csv: boolean;
			/**
			 * Perform Data Analysis
			 * @description Whether to perform data analysis and generate plots
			 * @default true
			 */
			perform_data_analysis: boolean;
			/**
			 * Id
			 * @description Unique observation identifier
			 */
			id: number;
			/**
			 * User Id
			 * @description ID of the user who submitted the observation
			 */
			user_id: number;
			/** @description Current observation status */
			status: components["schemas"]["ObservationStatusEnum"];
			/**
			 * Created On
			 * Format: date-time
			 * @description Timestamp of creation
			 */
			created_on: string;
			/**
			 * Updated On
			 * Format: date-time
			 * @description Timestamp of last update
			 */
			updated_on: string;
			/**
			 * Completed On
			 * @description Timestamp of completion
			 */
			completed_on?: string | null;
			/**
			 * Csv Download Url
			 * @description Pre-signed URL for downloading the CSV file (if receive_csv is True)
			 */
			csv_download_url?: string | null;
			/**
			 * Analysis Results Url
			 * @description Pre-signed URL for downloading the analysis results (if perform_data_analysis is True)
			 */
			analysis_results_url?: string | null;
			/**
			 * Data Download Url
			 * @description Pre-signed URL for downloading the observation data
			 */
			data_download_url?: string | null;
		};
		/**
		 * ObservationStatusEnum
		 * @description Enumeration for the status of an observation.
		 * @enum {string}
		 */
		ObservationStatusEnum:
			| "PENDING"
			| "IN_PROGRESS"
			| "COMPLETED"
			| "FAILED"
			| "CANCELLED";
		/**
		 * ObservationSubmissionRequest
		 * @description Payload for submitting an observation request.
		 */
		ObservationSubmissionRequest: {
			/** @description Observation submission payload */
			observation: components["schemas"]["ObservationCreate"];
			/** @description Optional guest requestor metadata */
			requestor?: components["schemas"]["UserCreate"] | null;
		};
		/**
		 * ObservationTypeEnum
		 * @description Enumeration for the type of an observation.
		 * @enum {string}
		 */
		ObservationTypeEnum:
			| "HOT_CALIBRATION"
			| "COLD_CALIBRATION"
			| "TARGET_OBSERVATION";
		/**
		 * ReferenceFrameEnum
		 * @description Enumeration for the velocity reference frame.
		 *
		 *     - TOPO: Topocentric frame, the raw, uncorrected frame of our antenna sitting exactly where it is on Earth. Used for calibration, debugging, and observing satellites.
		 *     - LSRK: Local Standard of Rest Kinematic frame, a theoretical frame moving in a perfect, circular orbit around the center of the Milky Way. It removes the Earth's spin, the Earth's orbit, and the Sun's messy localized wobbling. This should be our software's default setting, it is the standard for galactic radio astronomy. Anytime a user observes 1.42 GHz Milky Way Hydrogen or local 22 GHz galactic water masers, they must use LSRK.
		 *     - BARY: Barycentric frame, the center of mass of our Solar System. It removes the Earth's orbit and spin, but keeps the Sun's movement. Used for extragalactic observations. If the user points the telescope at a quasar billions of light-years away, or a pulsar in another galaxy, the local spinning of our Milky Way doesn't matter. Barycentric is the standard for anything outside our galaxy.
		 *     - HELIO: Heliocentric frame, the exact center of the Sun. It is incredibly close mathematically to Barycentric (since the Sun holds most of the Solar System's mass). However, many older optical astronomy catalogs and specific pulsar databases publish their coordinates and velocities in the Heliocentric frame. We include this for compatibility with those specific databases.
		 *     - GEO: Geocentric frame, the center of the Earth. It removes the Earth's daily rotation, but keeps the Earth's orbit around the Sun. Used when observing the Moon, near-Earth asteroids, or geostationary satellites.
		 * @enum {string}
		 */
		ReferenceFrameEnum: "TOPO" | "LSRK" | "BARY" | "HELIO" | "GEO";
		/**
		 * StatusResponse
		 * @description Generic status response for health checks and system status.
		 * @example {
		 *       "data": {
		 *         "active_observations": 3,
		 *         "uptime": 86400
		 *       },
		 *       "message": "System is operational",
		 *       "status": "healthy"
		 *     }
		 */
		StatusResponse: {
			/**
			 * Status
			 * @description Status indicator
			 */
			status: string;
			/**
			 * Message
			 * @description Optional message
			 */
			message?: string | null;
			/**
			 * Data
			 * @description Optional data payload
			 */
			data?: {
				[key: string]: unknown;
			} | null;
		};
		/**
		 * UserCreate
		 * @description Schema for creating a new user (API request).
		 * @example {
		 *       "auth_provider": "guest",
		 *       "email": "software@astrobeam.gr",
		 *       "user_id": "123456",
		 *       "username": "astro_test_user"
		 *     }
		 */
		UserCreate: {
			/**
			 * User Id
			 * @description Unique user identifier
			 */
			user_id: string;
			/**
			 * Username
			 * @description Username
			 */
			username: string;
			/**
			 * Email
			 * Format: email
			 * @description Email address
			 */
			email: string;
			/**
			 * Auth Provider
			 * @description Authentication provider
			 * @default guest
			 */
			auth_provider: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	list_observations_v1_observations__get: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of observations retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ObservationRead"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	submit_observation_v1_observations__post: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ObservationSubmissionRequest"];
			};
		};
		responses: {
			/** @description Observation request accepted */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ObservationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
			/** @description Telescope service unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_observation_v1_observations__observation_id__get: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string | null;
			};
			path: {
				observation_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Observation details retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ObservationRead"];
				};
			};
			/** @description Observation not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	cancel_observation_v1_observations__observation_id__delete: {
		parameters: {
			query?: never;
			header?: {
				authorization?: string | null;
			};
			path: {
				observation_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Observation cancelled successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Observation not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	health_check_v1_web_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description API is healthy */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StatusResponse"];
				};
			};
		};
	};
	get_system_status_v1_web_status_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description System status retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StatusResponse"];
				};
			};
		};
	};
	root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description API information retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StatusResponse"];
				};
			};
		};
	};
}
